
.powerline-fonts:
  type: git-repo
  url: https://github.com/powerline/fonts.git
  exact: true
  clone:
    args:
      - --depth=1

.vim/autoload/plug.vim:
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 720h
