#!/bin/bash

# Directory navigation
alias ~="cd ~"
alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."

# Listing
alias ll="ls -Fhlo"
alias la="ls -AFhlo"

# Directory creation
function mcd() { mkdir -p $1 && cd $1; }
