#!/bin/bash

# Directory navigation
alias ~="cd ~"
alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."

# Listing
alias ll="ls -Fhlo"
alias la="ls -AFhlo"

# Improved cat (requires https://github.com/rstacruz/hicat)
alias hi="hicat"

# Directory creation
function mcd() { mkdir -p $1 && cd $1; }

# Git
alias pull="git pull"
alias push="git push"
alias st="git status"
