#!/bin/bash

# Directory navigation
alias ~="cd ~"
alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."

# Listing
alias ll="ls -Fhlo"
alias la="ls -AFhlo"

# Improved cat (requires https://github.com/rstacruz/hicat)
alias hi="hicat"

# Directory creation
function mcd() { mkdir -p "$1" && cd "$1"; }

# Directory removal
alias rmr="rm -rf"

# Git
alias pull="git pull"
alias push="git push"
alias st="git status"
alias nuke-local-branches="git br | xargs -L1 echo | while read line; do if [[ ! \"\$line\" =~ ^\s*\* ]] ; then git br -d \"\$line\"; fi; done"
