#!/bin/bash

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Set up Sublime Text 2 as an editor (requires command line tool)
if [ ! `which subl`  == "" ]; then
    export EDITOR='subl -w'
fi

# Initialise rbenv if present
if [ ! `which rbenv`  == "" ]; then
    eval "$(rbenv init -)"
fi

# Initialise nvm if present
if [ -f "$(brew --prefix nvm)/nvm.sh" ]; then
    mkdir -p ~/.nvm
    export NVM_DIR=~/.nvm
    source "$(brew --prefix nvm)/nvm.sh"
fi
