#!/bin/bash

declare -a files=(
    $HOME/.dotfiles/bash/aliases
    $HOME/.dotfiles/bash/exports
    $HOME/.dotfiles/bash/options
    $HOME/.dotfiles/bash/paths
    $HOME/.dotfiles/bash/prompt
)

# If these files are readable, source them
for index in ${!files[*]}; do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

# Only use `brew` after it has been added to the PATH
bash_completion_path="$(brew --prefix)/etc/bash_completion"

# Source Bash completion (installed via Homebrew)
if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
fi
