#!/bin/bash

function prompt_git_info () {
    if [ ! `get_git_branch` == "" ]; then
        dirty_indicator=$([ "$(is_git_tree_dirty)" == "" ] && echo "" || echo "!")
        echo " [$(get_git_branch)$dirty_indicator]"
    fi
}

PS1="\[$(tput setaf 8)\]\$(pwd_truncated)\$(prompt_git_info)$ \[$(tput sgr0)\]"
